export const TOGGLE_NAVIGATION_VISIBILITY = 'TOGGLE_NAVIGATION_VISIBILITY';

export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_PENDING = 'GET_MOVIES_PENDING';
export const GET_MOVIES_FULFILLED = 'GET_MOVIES_FULFILLED';
export const GET_MOVIES_REJECTED = 'GET_MOVIES_REJECTED';

export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const SEARCH_MOVIE_PENDING = 'SEARCH_MOVIE_PENDING';
export const SEARCH_MOVIE_FULFILLED = 'SEARCH_MOVIE_FULFILLED';
export const SEARCH_MOVIE_REJECTED = 'SEARCH_MOVIE_REJECTED';
