export const GET_TMDB_CONFIG = 'GET_TMDB_CONFIG'
export const GET_TMDB_CONFIG_PENDING = 'GET_TMDB_CONFIG_PENDING'
export const GET_TMDB_CONFIG_FULFILLED = 'GET_TMDB_CONFIG_FULFILLED'
export const GET_TMDB_CONFIG_REJECTED = 'GET_TMDB_CONFIG_REJECTED'

export const LOGIN = 'LOGIN'
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED'
export const LOGIN_REJECTED = 'LOGIN_REJECTED'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_PENDING = 'LOGOUT_PENDING'
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED'
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED'

export const HIDE_NAVIGATION = 'HIDE_NAVIGATION'
export const TOGGLE_NAVIGATION = 'TOGGLE_NAVIGATION'

export const GET_MOVIES = 'GET_MOVIES'
export const GET_MOVIES_PENDING = 'GET_MOVIES_PENDING'
export const GET_MOVIES_FULFILLED = 'GET_MOVIES_FULFILLED'
export const GET_MOVIES_REJECTED = 'GET_MOVIES_REJECTED'

export const SEARCH_MOVIE = 'SEARCH_MOVIE'
export const SEARCH_MOVIE_PENDING = 'SEARCH_MOVIE_PENDING'
export const SEARCH_MOVIE_FULFILLED = 'SEARCH_MOVIE_FULFILLED'
export const SEARCH_MOVIE_REJECTED = 'SEARCH_MOVIE_REJECTED'
